Fix matrix build workflow and enhance error handling
Corrected a typo in the job name and adjusted matrix-related logic to support multiple architectures (linux/amd64 and linux/arm64). Added validation to ensure generated JSON is valid, improving reliability and maintainability of the workflow.

diff --git a/.github/workflows/extensions-builder.yml b/.github/workflows/extensions-builder.yml
--- a/.github/workflows/extensions-builder.yml
+++ b/.github/workflows/extensions-builder.yml
@@ -288,7 +288,7 @@ jobs:
         
 
 
-  make-matix-build-extensions:
+  make-matrix-build-extensions:
     needs: [ setup, create-multi-arch-manifest ]
     runs-on: ubuntu-latest
     outputs:
@@ -312,19 +312,31 @@ jobs:
               extension: .[0].extension,
               pgrx_version: .[0].pgrx_version,
               extension_version: .[0].extension_version,
+              "platform": "linux/amd64"
+              pg_versions: map(.pg_version) | unique
+            })+map({
+              extension: .[0].extension,
+              pgrx_version: .[0].pgrx_version,
+              extension_version: .[0].extension_version,
+              "platform": "linux/arm64"
               pg_versions: map(.pg_version) | unique
             }) |
               {
                 "include": .
               }')
           
-          echo "matrix=$build_matrix" >> $GITHUB_OUTPUT
+          if echo "$build_matrix" | jq empty; then
+            echo "matrix=$build_matrix" >> $GITHUB_OUTPUT
+          else
+            echo "Error: Invalid JSON matrix generated"
+            exit 1
+          fi
 
-  build-extensions:
-    needs: make-matix-build-extensions
+  build-extensions-arch:
+    needs: make-matrix-build-extensions
     runs-on: ubuntu-latest
     strategy:
-      matrix: ${{ fromJson(needs.make-matix-build-extensions.outputs.matrix) }}
+      matrix: ${{ fromJson(needs.make-matrix-build-extensions.outputs.matrix) }}
       fail-fast: false
     steps:
       - uses: actions/checkout@v4
